### ISSUE TITLE
Unable to reference CUI project

### ISSUE THREAD

**Issue by aijkl** [CircuitLord/DesktopPortal#10]
![image](https://user-images.githubusercontent.com/51302983/125181789-5152d000-e243-11eb-875f-75d3343d16dd.png)
![image](https://user-images.githubusercontent.com/51302983/125181748-fe791880-e242-11eb-906f-10c0263cb664.png)

Hi, I'm a C # developer who isn't mature in Unity.
Unable to reference CUI project
You can see the reference to the CUI Project by opening the AssemblyCharp Project reference in the Object Browser.
However, I cannot refer to CUI.CUIManager with using CUI or FullPath.

Please tell me how to fix it if you like
Visual Studio 2019
Unity 2020.3.12f1

**Comment by CircuitLord** [comment]
Hm, that's very strange. It seems like the reference to stuff like TextMeshPro isn't working either, which makes me think it's some issue besides CUI.

I can fire up the project when I get a chance and see if I get any of those errors. From what I can tell it just seems like the DLLs aren't all loading. Do you have any errors in Unity besides just compliation errors? (maybe like failed imports or something?)

**Comment by aijkl** [comment]
![image](https://user-images.githubusercontent.com/51302983/125181964-df7b8600-e244-11eb-8099-86d955b84e7c.png)
Oddly enough, the compilation on the Unity side succeeds.
I don't know much about Unity, but is there a function to run the last successfully compiled assembly?
If not, is this a problem with Visual Studio?

What I did was git clone https://github.com/CircuitLord/DesktopPortal
The only action I took was to open the Unity Project after doing the git clone . I did not do anything else.
Sorry for the confusing English, I am using DeepL.

**Comment by CircuitLord** [comment]
It seems like some sort of issue with Visual Studio then, maybe try regenerating the project files in Unity?
![image](https://user-images.githubusercontent.com/11892359/125182221-cd143480-e1d1-11eb-8504-5915fb64cc2a.png)
Other than that, I'm not really sure what the issue could be unfortunately.

**Comment by aijkl** [comment]
![image](https://user-images.githubusercontent.com/51302983/125185167-1611ca80-e25e-11eb-955e-09771f3e6edf.png)
NET IDE of Jetbrains after watching this video, so I installed it and tried to use it.
NET IDE of Jetbrains, so I installed it and tried to use it. It worked, I don't know why I couldn't use VisualStudio, but it worked so I won't think about it.

If you have a student account, you can use Jetbrains products for free, which is good.
If you are trying to edit DesktopPortal and have problems with references, installing "Rider https://www.jetbrains.com/ja-jp/rider/" may solve the problem.
